name: Deploy to k3s

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Check cluster
      run: |
        kubectl get nodes

    - name: Deploy Nginx app
      run: |
        kubectl apply -f k8s/nginx-config.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/svc.yaml
        kubectl apply -f k8s/ingress.yaml

    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get svc
        kubectl get ingress